# Generated by Django 4.1 on 2025-08-06 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Canton',
                'verbose_name_plural': 'Cantones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.canton')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('icono', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('pertenece', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigodatabooks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100, verbose_name='1er Apellido')),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True, verbose_name='2do Apellido')),
                ('extranjero', models.BooleanField(default=False)),
                ('identificacion', models.CharField(blank=True, max_length=13, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('madre', models.CharField(blank=True, max_length=100, null=True)),
                ('padre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle Principal')),
                ('direccion2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle Secundaria')),
                ('num_direccion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefonos Moviles')),
                ('telefono_conv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefonos Fijos')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correos Electronicos')),
                ('email1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correos Electronicos')),
                ('email2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correos Electronicos')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='persona_imagen/')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.canton', verbose_name='Canton de Nacimiento')),
                ('cantonresid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CantondeResidencia', to='appturopamiestilo.canton', verbose_name='Canton de Residencia')),
                ('estadocivil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.estadocivil', verbose_name='Estado Civil')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.nacionalidad')),
                ('nivelacademico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.nivelacademico', verbose_name='Nivel Academico')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.parroquia', verbose_name='Parroquia')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.provincia', verbose_name='Provincia de Nacimiento')),
                ('provinciaresid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProvinciadeResidencia', to='appturopamiestilo.provincia', verbose_name='Provincia de Residencia')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.sector', verbose_name='Sector Direccion')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.sexo')),
                ('tipoidentificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.tipoidentificacion')),
                ('tiposangre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.tiposangre', verbose_name='Tipo Sangre')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.perfil')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ModuloPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.modulo')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.provincia'),
        ),
        migrations.CreateModel(
            name='ActividadComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.sectorcomercial')),
            ],
        ),
        migrations.CreateModel(
            name='AccesoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresar', models.BooleanField(default=True)),
                ('editar', models.BooleanField(default=True)),
                ('ver', models.BooleanField(default=True)),
                ('eliminar', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.modulo')),
                ('perfilpersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appturopamiestilo.perfilpersona')),
            ],
        ),
    ]
